title: Peter Liniker
description: '"Its inside is bigger than its outside..."'
baseurl: ""
url: "http://pliniker.github.io"
github_username:  pliniker

timezone: EST5EDT

markdown: kramdown

permalink: /post/:title/

gems:
  - jekyll-redirect-from
  - jekyll-feed

theme: jekyll-theme-modernist

google_analytics: UA-91688143-1
show_downloads: false
