title: Peter Liniker
description: >
  If you think without writing, you only think you're thinking. - Leslie Lamport.
baseurl: ""
url: "http://pliniker.github.io"
github_username:  pliniker

timezone: EST5EDT

markdown: kramdown

permalink: /post/:title/

gems:
  - jekyll-redirect-from
  - jekyll-feed

