title: Peter Liniker
description: >
  If you think without writing, you only think you're thinking. - Leslie Lamport.
baseurl: ""
url: "http://pliniker.github.io"
github_username:  pliniker

timezone: EST5EDT

markdown: kramdown

permalink: /post/:title/

gems:
  - jekyll-redirect-from
  - jekyll-feed

collections:
  my_categories:
    output: true
    permalink: /category/:name/

defaults:
  -
    scope:
      path: ""
      type: my_categories
    values:
      layout: my_category
