title: Peter Liniker
description: ""
baseurl: ""
url: "http://pliniker.github.io"
github_username: pliniker

timezone: EST5EDT

markdown: kramdown

permalink: /post/:title/

plugins:
  - jekyll-redirect-from
  - jekyll-feed

theme: jekyll-theme-modernist

show_downloads: false
